### ISSUE TITLE
Plugin not adding user in Mailchimp properly

### ISSUE THREAD

**Issue by wwwdavid34** [bayamsell/keycloak-mailchimp#3]
The pseudo user I created using my email address with registration form pop up in mailchimp user list. 

Hoever, the first/last name was not test/test as I input in the registration form, but the old record that I "archived" in mailchimp.

After I removed my archive account PERMANENTLY in mailchimp, I am no longer able to trigger new user creation in mailchimp from keycloak.

**Comment by stephane-segning** [comment]
This is probably related to the user you created which is cached in mailchimp. This plugin just call another one, which call mailchimp. Please, open a PR on https://github.com/banana-j/bananaj if things persists.
